global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 로컬에서 앱이 8080으로 뛰는 전제
      - targets: ['host.docker.internal:8080']
